if (!estaAutenticado()) window.location.href = "login.html";
const perfilForm=document.getElementById("perfilForm"), perfisLista=document.getElementById("perfisLista"), perfisMsg=document.getElementById("perfisMsg");let perfis=[];
const safePerfil=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function avisarPerfil(t,err=false){perfisMsg.hidden=!t;perfisMsg.textContent=t;perfisMsg.className="faq-message"+(err?" error":"");}
function limparPerfil(){perfilForm.reset();document.getElementById("perfilId").value="";document.getElementById("perfilAtivo").checked=true;document.getElementById("perfilTitulo").textContent="Criar perfil";document.getElementById("perfilCancelar").hidden=true;}
function desenharPerfis(){perfisLista.innerHTML=perfis.length?perfis.map(p=>`<article class="category-card"><div><h3>${safePerfil(p.nome)}</h3><p>${safePerfil(p.descricao||"Sem descrição")}</p><span class="priority-badge">${p.ativo?"Ativo":"Inativo"} · ${(p.permissoes||[]).length} permissões</span></div><div class="button-group"><button class="btn btn-secondary profile-edit" data-id="${p.id}">Editar</button><button class="btn btn-secondary profile-delete" data-id="${p.id}">Desativar</button></div></article>`).join(""):'<div class="empty-state"><p>Nenhum perfil personalizado cadastrado.</p></div>';}
async function carregarPerfis(){perfis=await apiGetJson("/api/perfis");desenharPerfis();}
async function iniciarPerfis(){try{const me=await apiGetJson("/api/usuarios/me");document.getElementById("btnLogout").addEventListener("click",logout);document.querySelectorAll("[data-admin-only]").forEach(x=>x.hidden=me.perfil!=="ADMIN");document.querySelectorAll("[data-permission]").forEach(x=>x.hidden=!(me.permissoes||[]).includes(x.dataset.permission));if(me.perfil!=="ADMIN"){perfilForm.hidden=true;avisarPerfil("Somente administradores podem alterar perfis.",true);return;}await carregarPerfis();}catch(e){avisarPerfil(getMensagemErroAmigavel(e.status||0),true);}}
document.getElementById("perfilCancelar").addEventListener("click",limparPerfil);
perfilForm.addEventListener("submit",async e=>{e.preventDefault();const id=document.getElementById("perfilId").value,payload={nome:document.getElementById("perfilNome").value.trim(),descricao:document.getElementById("perfilDescricao").value.trim(),permissoes:Array.from(perfilForm.querySelectorAll(".permission-list input:checked")).map(x=>x.value),ativo:document.getElementById("perfilAtivo").checked};try{const r=await apiRequest(id?`/api/perfis/${id}`:"/api/perfis",{method:id?"PUT":"POST",body:JSON.stringify(payload)});if(!r.ok)throw{status:r.status};limparPerfil();avisarPerfil("Perfil salvo.");await carregarPerfis();}catch(err){avisarPerfil(getMensagemErroAmigavel(err.status||0),true);}});
perfisLista.addEventListener("click",async e=>{const ed=e.target.closest(".profile-edit"),del=e.target.closest(".profile-delete");if(ed){const p=perfis.find(x=>x.id===Number(ed.dataset.id));if(!p)return;document.getElementById("perfilId").value=p.id;document.getElementById("perfilNome").value=p.nome;document.getElementById("perfilDescricao").value=p.descricao||"";document.getElementById("perfilAtivo").checked=p.ativo;perfilForm.querySelectorAll(".permission-list input").forEach(x=>x.checked=(p.permissoes||[]).includes(x.value));document.getElementById("perfilTitulo").textContent="Editar perfil";document.getElementById("perfilCancelar").hidden=false;perfilForm.scrollIntoView({behavior:"smooth"});}if(del&&confirm("Desativar este perfil? Ele precisa estar sem usuários atribuídos.")){const r=await apiRequest(`/api/perfis/${del.dataset.id}`,{method:"DELETE"});if(!r.ok)avisarPerfil("Não foi possível desativar. Reatribua os usuários que usam este perfil e tente novamente.",true);else{avisarPerfil("Perfil desativado.");await carregarPerfis();}}});
iniciarPerfis();
